### ISSUE TITLE
Enable Keyboard Light Control Support

### ISSUE THREAD

**Issue by GiowGiow** [AlexIII/tcc-g15#1]
Keyboard light control would be a really good addition to stop using AWCC altogether. 
 
Do you have any insights or tips you could give on how you reverse engineered the constants and methods from AWCC software? I would happily research this in my spare time

**Comment by AlexIII** [comment]
Hi!
Maybe we have different laptops? Mine has a dedicated key (fn + f5) that controls keyboard backlight. I didn't even know it could be controlled from AWCC.

You can access WMI functions in python like this (run as Administrator)

```python
import wmi
awccClass = wmi.WMI(namespace="root\WMI").AWCCWmiMethodFunction
awcc = awccClass()[0]
```

Then you can just `print(awcc )` and it will print the available methods for you. The meaning of the arguments and the return value is not documented there. In order to understand that part I had to decompile "AWCC server" (it's in C#). But it uses very limited subset of available WMI methods (three, to be exact). I drafted my findings [here](https://github.com/AlexIII/tcc-g15/blob/master/WMI-AWCC-doc.md).

Since I didn't need to control the backlight, that's where I stopped.

**Comment by GiowGiow** [comment]
Thanks for the info on reverse engineering, I really appreciate it! 

I think we have the same model, I also have the dedicated key to control the keyboard backlight, but it only works with the AWCC running in the background, so to ditch that software entirely I want to find a way to copy that behavior. 

Thinking about it a little more, maybe AWCC just monitors the clicks and calls some proprietary AlienFX API. I'm looking into this project here: https://github.com/T-Troll/alienfx-tools . Maybe it will work, I still have to try.

**Comment by AlexIII** [comment]
>  I also have the dedicated key to control the keyboard backlight, but it only works with the AWCC running in the background
I have AWCC removed from my system, but the backlight button works fine. Here, I should note that AWCC actually comprises of (at least) three components: GUI app which talks to Server app which talks to WMI driver. I wrote my program to replace the first two, but the third is still required, so maybe it also handles the backlight key, I don't know...
I'll pin this thread, so others could see it too.
