### ISSUE TITLE
Does G Mode just control fans? 

### ISSUE THREAD

**Issue by Raspytooth28** [AlexIII/tcc-g15#4]
Hi this isn't an issue but more of a question, I was wondering if when enabling g mode with this program, is it exactly the same as the AWCC G mode where the GPU will boost up to its maximum wattage, also do any of the other thermal modes do anything? I'm refering to your findings here: https://github.com/AlexIII/tcc-g15/blob/master/WMI-AWCC-doc.md

**Comment by AlexIII** [comment]
Hi! The program does activate the 'real' G mode, so it should be exactly the same as with AWCC.
However, I have my doubts this mode has anything to do with the GPU power limit. In my experience, the only thing that controls the power limit is the external power supply. Here's approximate numbers I acquired from my laptop when experimenting. The GPU wattage as reported by GMiner.

Battery power - ~50w
PSU connected, battery is charging - ~100w
PSU connected, battery is not charging - ~125w

**Comment by Raspytooth28** [comment]
> 

Okay that's great, so I can replace AWCC with your program then because it keeps crashing all the time, and i only use AWCC for G mode and temp monitoring anyways, I saw somewhere that G mode controlled the GPU running at its max wattage but maybe that information is incorrect, Would you be able to implement the G key changing between balanced and G mode? If you could implement this I'd happily donate some money for your time.

**Comment by AlexIII** [comment]
Thank you for your kind offer, but I don't accept donations. I will look into adding this feature when I have time, provided it is at all possible to capture this special function key. You can leave this repo a star if you liked the project.

**Comment by Raspytooth28** [comment]
Okay thank you for looking into it, I've already starred the repo.

**Comment by AlexIII** [comment]
Right, I've looked into it. Turns out it is indeed possible to capture the G-mode keyboard key with the `pynput` library. The problem is, it looks like this library was used in some malware so now windows defender detects a program with this lib as 'keylogger malware'. I cannot use this solution, because it would be a huge turn-down for the users.
I couldn't find alternative solutions, so for now it's a 'no' for this feature, but I'm open for suggestions.

**Comment by T-Troll** [comment]
@AlexIII I can help you to implement REAL g-mode (it's not about power mode switch only).
I see you are using WMI approach as well as me (now, before i RE ACPI BIOS0, but you're still at the beginning of the way i pass already.
Check, please - https://github.com/T-Troll/alienfx-tools

**Comment by AlexIII** [comment]
@T-Troll what do you mean "REAL g-mode"? The one that's provided via WMI works fine for me.

**Comment by T-Troll** [comment]
Switching mode to 0xab via `Thermal_Control` is not, really, G-mode, You also need to alter it via `GameShiftStatus`, and, for some systems like G5SE, issue Q13 call.

**Comment by AlexIII** [comment]
Yes, you've already said that it's "not real". My question is, how "real" G-mode and "not real" are different?

**Comment by T-Troll** [comment]
Depend on the model.

I case you just change mode, it alters fan profile and PWM settings.
But 0x25th function also change GPU settings and power distribution in common.

For 5515, as far as i see into BIOS dump (AX27 function), it changes ECV SPI data as well. No GPU changes in this case.

**Comment by AlexIII** [comment]
> it changes ECV SPI data

Do you know what effect it has on the system? Like, does it increases performance or CPU clock or what?

It's just, I never intended this program to do _exactly_ what AWCC does. It's primary function is to control fans. That's it.

**Comment by AlexIII** [comment]
Oh, I think I'm starting to get what you mean. I myself only have G15 5515 and cannot check anything other than that model. That's why I specifically put notes that this program is _not_ universal for dell laptops. I do realize that other models may have (and, apparently, _do_ have) different schemes for controlling what we call "G-mode". Specifically for 5515, though, I can say to a certainty that there's nothing more then just switching thermal mode via `Thermal_Control WmiMethodId(21)` because I disassembled the AWCC service program that controls thermal modes. It just uses 3 functions from WMI interface in the whole program.

```
Thermal_Information WmiMethodId(20)
GetFanSensors WmiMethodId(19)
Thermal_Control WmiMethodId(21)
```
Again, it's only applicable to 5515, other models have different services and may use additional WMI methods.
I never really have had a goal to support as many dell laptops as possible, it's just a small utility that I made for myself and wanted to share =)

**Comment by T-Troll** [comment]
It is universal for most modern systems (both G, Alienware and even Aurora).

So you are following the right way, but i wonder why you didn't find `GameShiftStatus (0x25)` method - it SHOULD be used into AWCCService!
Maybe 55 have its own AWCC mod without it?

Anyway, feel free to check https://github.com/T-Troll/alienfx-tools/tree/master/alienfan-tools/alienfan-SDK (especially `alienfan-controls.h` - it has full zoo function list and description.

PS: It will be nice if you port your app for Linux - it's not so easy for me...

**Comment by AlexIII** [comment]
> but i wonder why you didn't find GameShiftStatus (0x25) method 

Its been almost 2 years since I've looked into the original awcc software. Maybe something have changed. I will try to replicate my steps to see if I missed anything, that is, when I have time to do so.

Thank you for the hints.

**Comment by T-Troll** [comment]
You are welcome!

More alternatives always better.

**Comment by cemkaya-mpi** [comment]
> PS: It will be nice if you port your app for Linux - it's not so easy for me...

@T-Troll I would be interested in porting the functionality to linux, especially since the gpu is throttled to 45Watts (by BIOS ?) after it reaches 87 °C, and stays that way even after it cools down. I have not found any solution to restore the default power limit of 115Watts besides rebooting so far. Though I believe WMI does not exist for linux, and both projects use WMI as far as I understand. In this case, I guess using ACPI methods will be necessary. How would one go about porting the functionality? Any hint would be appreciated!

I checked `alienfan-controls.h` but I am not sure what to do.

**Comment by T-Troll** [comment]
@cemkaya-mpi Some Linux has WMI (PnP) support AFAIR.
You can also check my older V1 fan control here - https://github.com/T-Troll/alienfx-tools/tree/master/alienfan-tools/alienfan-SDK 
It uses direct ACPI method calls via kernel driver, less universal (some systems have different method names), but faster.
You can use it as a reference of ACPI method names and parameters.

**Comment by cemkaya-mpi** [comment]
I have found the relevant ACPI calls from the SDK, and used @AlexIII 's findings about the power modes to add a power mode switch to my simple linux app. It is by no means complete, but one can at least set keyboard backlight and power mode with the app on linux. If that is alright with both of you, I will publish it on github and AUR.

**Comment by T-Troll** [comment]
@cemkaya-mpi 
Feel free. I have open license.

**Comment by AlexIII** [comment]
@cemkaya-mpi the actual code in this repo is under GPL v3. The principles behind it, docs, descriptions and comments are not subject to licensing (you can do whatever you like).

**Comment by Borealis404** [comment]
> It's been almost 2 years since I've looked into the original awcc software. Maybe something have changed. I will try to replicate my steps to see if I missed anything, that is, when I have time to do so.
I'm using G15 5515 and here's details:
In AWCC settings, you could find "GameShift Cooling Option" and it gives you 2 option : Rapid Cool & High Performance. Rapid Cool is fan-only.(or otherwise?)
There's definitely in there in latest AWCC.

**Comment by poly000** [comment]
Hi. is there any updates on this issue?

**Comment by AlexIII** [comment]
What issue? It was a question. The answer was given. Closed.

**Comment by mokurin000** [comment]
> What issue? It was a question. The answer was given. Closed.

Then we should have an issue to also trigger power profile of G mode

**Comment by AlexIII** [comment]
> Then we should have an issue to also trigger power profile of G mode

Look, I only own 5515 and my experiments with the driver/WMI API did not show any way to control 'power profile' separately of G-mode or at all really. As I have mentioned earlier, on my machine, the GPU power limit is controlled automatically by plugging/unplugging the external power supply.
I do understand that other G15 models can have different implementations of power management, but I have no means to research and test it.
That being said, if anyone wants to contribute and add that functionality to the app, PRs are always welcome.
